In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
os.chdir("C:\\Users\\Dell\\Downloads")
filename = 'true.csv'
df = pd.read_csv(filename)

In [3]:
df.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [5]:
features = ['text', 'subject']
for feature in features:
    df[feature] = df[feature].fillna('')

In [6]:
def combined_features(row):
    return row['title']+" "+row['text']+" "+row['subject']

df["combined_features"] = df.apply(combined_features, axis =1)

In [7]:
df.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date                                  combined_features  
0  December 31, 2017   As U.S. budget fight looms, Republicans flip t...  
1  December 29, 2017   U.S. military to accept transgender recruits o...  
2  December 31, 2017   Senior U.S. Republican senator: 'Let Mr. Muell...  
3  December 30, 2017   FBI Russia probe helped by Australian diplomat...  
4  December 29, 2017   Trump wants Postal Service to charge 'much mor...

In [8]:
df1 = pd.DataFrame(df["combined_features"])

In [9]:
df1

combined_features
0      As U.S. budget fight looms, Republicans flip t...
1      U.S. military to accept transgender recruits o...
2      Senior U.S. Republican senator: 'Let Mr. Muell...
3      FBI Russia probe helped by Australian diplomat...
4      Trump wants Postal Service to charge 'much mor...
...                                                  ...
21412  'Fully committed' NATO backs new U.S. approach...
21413  LexisNexis withdrew two products from Chinese ...
21414  Minsk cultural hub becomes haven from authorit...
21415  Vatican upbeat on possibility of Pope Francis ...
21416  Indonesia to buy $1.14 billion worth of Russia...

[21417 rows x 1 columns]

### ENTER TITLE : 

In [10]:
v = input("Enter title/news of which you want recommendations for: ")

Enter title of news you want recommendations for: Postal Service


In [11]:
df1=df1.append({"combined_features":v},ignore_index=True)

In [12]:
df1
cv = CountVectorizer()
count_matrix = cv.fit_transform(df1["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
cosine_sim = cosine_similarity(count_matrix)

In [14]:
cosine_sim

array([[1.        , 0.79343817, 0.72259769, ..., 0.64468523, 0.57171516,
        0.        ],
       [0.79343817, 1.        , 0.70823947, ..., 0.62244542, 0.53260179,
        0.02913033],
       [0.72259769, 0.70823947, 1.        , ..., 0.66310139, 0.50314754,
        0.        ],
       ...,
       [0.64468523, 0.62244542, 0.66310139, ..., 1.        , 0.56754409,
        0.        ],
       [0.57171516, 0.53260179, 0.50314754, ..., 0.56754409, 1.        ,
        0.        ],
       [0.        , 0.02913033, 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [15]:
recommended_list = list(enumerate(cosine_sim[-1]))

In [16]:
recommended_list

[(0, 0.0),
 (1, 0.02913033260329736),
 (2, 0.0),
 (3, 0.0),
 (4, 0.2898953050787322),
 (5, 0.0),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.010841422245040153),
 (12, 0.0),
 (13, 0.0),
 (14, 0.05100153006885344),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.027628948199776883),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.015106498551743829),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.012260943177452603),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.019651334235785942),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.01557186649660749),
 (68, 0.0),
 (69, 0.029721914913888203),
 (70,

In [17]:
sorted_recommended_list = sorted(recommended_list, key=lambda x:x[1], reverse=True)

In [18]:
sorted_recommended_list=sorted_recommended_list[1:]

In [21]:
sorted_recommended_list

[(4, 0.2898953050787322),
 (7546, 0.2128141326896871),
 (15358, 0.19230769230769232),
 (10582, 0.1839418018454897),
 (4866, 0.16876318513890357),
 (18546, 0.1678362716593378),
 (20163, 0.16035674514745463),
 (2097, 0.154713186938819),
 (10342, 0.1477635311413854),
 (11498, 0.1437398936440172),
 (9050, 0.13837968120433275),
 (20006, 0.13130643285972257),
 (20296, 0.12815364865751414),
 (3782, 0.1259881576697424),
 (17759, 0.12374948760083872),
 (16385, 0.12262786789699315),
 (17015, 0.12126781251816646),
 (1955, 0.12093481103138008),
 (16846, 0.12),
 (1018, 0.11995202878081342),
 (2084, 0.11726446574911564),
 (19988, 0.11624763874381927),
 (10583, 0.11536023921124004),
 (737, 0.11025662901212054),
 (6004, 0.11009637651263605),
 (10155, 0.1099672391311716),
 (20005, 0.10690449676496974),
 (21324, 0.10461315619318828),
 (16673, 0.10397504898200725),
 (18519, 0.10194414990458771),
 (2728, 0.10062305898749054),
 (15683, 0.10044292546128847),
 (18081, 0.09690031662230184),
 (8491, 0.09678678

In [19]:
def get_title_from_indexee(index):
    return df['title'][index]

In [20]:
i=0
for movie in sorted_recommended_list:
    i=i+1
    if i>11:
        break
    print(get_title_from_indexee(movie[0]))
   

Trump wants Postal Service to charge 'much more' for Amazon shipments
Secret Service says no weapon was found in Trump incident
Russian spy agency building catches fire in Moscow: RIA
Secret Service investigating incident at Trump rally: White House
White House intruder was on grounds for 16 minutes before arrest: Secret Service
Catalonia government says 893 injured in clashes during banned referendum
CSX resumes normal train operations into parts of Georgia: statement
Trump tweets thanks to Steve Bannon for service and role in campaign against Clinton
Secret Service manpower shortage as campaigns ramp up
Uzbek leader says he will curb power of state security service
U.S. military says will not disclose details on injured service members
